"""
pages/Reports.py
-----------------
Browse and re-download previously generated PDF patient reports.
"""

import streamlit as st
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))
from utils.report_generator import load_report_index

st.set_page_config(page_title="Reports | Heart Attack Prediction Agent", page_icon="📄", layout="wide")

st.title("📄 Generated Reports")
st.caption("All PDF risk assessment reports generated by this agent.")

df = load_report_index()

if df.empty:
    st.info(
        "No reports generated yet. Go to the main page, run a prediction, "
        "and click 'Generate PDF Report'."
    )
    st.stop()

col1, col2 = st.columns([2, 1])
with col1:
    search = st.text_input("🔎 Search by patient name")
with col2:
    risk_filter = st.multiselect("Risk Level", options=["High Risk", "Moderate Risk", "Low Risk"])

filtered = df.copy()
if search:
    filtered = filtered[filtered["patient_name"].str.contains(search, case=False, na=False)]
if risk_filter:
    filtered = filtered[filtered["risk_level"].isin(risk_filter)]

filtered = filtered.sort_values("timestamp", ascending=False)

st.markdown(f"**{len(filtered)}** report(s) found")
st.markdown("---")

for _, row in filtered.iterrows():
    risk_color = {"High Risk": "🔴", "Moderate Risk": "🟠", "Low Risk": "🟢"}.get(row["risk_level"], "⚪")
    with st.container():
        c1, c2, c3, c4 = st.columns([3, 2, 2, 2])
        c1.markdown(f"**{row['patient_name']}**  \n`{row['report_id']}`")
        c2.markdown(f"{row['timestamp']}")
        c3.markdown(f"{risk_color} {row['risk_level']} ({row['risk_percent']}%)")
        if os.path.exists(row["pdf_path"]):
            with open(row["pdf_path"], "rb") as f:
                c4.download_button(
                    "⬇️ Download",
                    data=f.read(),
                    file_name=os.path.basename(row["pdf_path"]),
                    mime="application/pdf",
                    key=f"dl_{row['report_id']}",
                )
        else:
            c4.caption("File missing")
        st.markdown("---")

st.download_button(
    "⬇️ Export report index as CSV",
    data=filtered.to_csv(index=False),
    file_name="report_index_export.csv",
    mime="text/csv",
)
