"""
utils/report_generator.py
--------------------------
Generates patient-facing PDF reports and appends a record to
reports/patient_reports.csv for tracking.
"""

import os
import uuid
import pandas as pd
from datetime import datetime

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)

from utils.predictor import FEATURE_LABELS

REPORTS_DIR = os.path.join(os.path.dirname(__file__), "..", "reports")
REPORTS_CSV = os.path.join(REPORTS_DIR, "patient_reports.csv")

REPORT_COLUMNS = [
    "report_id", "timestamp", "patient_name", "prediction",
    "risk_percent", "risk_level", "pdf_path",
]


def _ensure_reports_file():
    os.makedirs(REPORTS_DIR, exist_ok=True)
    if not os.path.exists(REPORTS_CSV):
        pd.DataFrame(columns=REPORT_COLUMNS).to_csv(REPORTS_CSV, index=False)


def generate_pdf_report(patient: dict, result: dict, patient_name: str = "Unnamed",
                          notes: str = "") -> str:
    """Create a PDF report for a patient's prediction and save to reports/.
    Returns the path to the generated PDF."""
    _ensure_reports_file()

    report_id = str(uuid.uuid4())[:8]
    timestamp = datetime.now()
    filename = f"report_{report_id}.pdf"
    pdf_path = os.path.join(REPORTS_DIR, filename)

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "TitleStyle", parent=styles["Title"], fontSize=20, spaceAfter=6
    )
    subtitle_style = ParagraphStyle(
        "Subtitle", parent=styles["Normal"], fontSize=10, textColor=colors.grey
    )
    section_style = ParagraphStyle(
        "Section", parent=styles["Heading2"], spaceBefore=16, spaceAfter=8
    )
    risk_color_map = {"High Risk": colors.HexColor("#D64545"),
                       "Moderate Risk": colors.HexColor("#E0A93E"),
                       "Low Risk": colors.HexColor("#3E9E5E")}
    risk_style = ParagraphStyle(
        "RiskStyle", parent=styles["Heading1"], fontSize=22,
        textColor=risk_color_map.get(result.get("risk_level"), colors.black),
        spaceAfter=4,
    )

    doc = SimpleDocTemplate(pdf_path, pagesize=letter,
                             topMargin=0.6 * inch, bottomMargin=0.6 * inch)
    elements = []

    elements.append(Paragraph("Heart Attack Risk Assessment Report", title_style))
    elements.append(Paragraph(
        f"Generated: {timestamp.strftime('%B %d, %Y at %H:%M')} &nbsp;|&nbsp; Report ID: {report_id}",
        subtitle_style
    ))
    elements.append(Spacer(1, 16))

    elements.append(Paragraph(f"Patient: {patient_name}", section_style))
    elements.append(Paragraph(
        f"Risk Level: {result.get('risk_level')} ({result.get('risk_percent')}% probability)",
        risk_style
    ))
    elements.append(Spacer(1, 10))

    elements.append(Paragraph("Clinical Input Values", section_style))
    table_data = [["Parameter", "Value"]]
    for col, label in FEATURE_LABELS.items():
        table_data.append([label, str(patient.get(col, "-"))])

    t = Table(table_data, colWidths=[3.4 * inch, 2.6 * inch])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#2C3E50")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, colors.HexColor("#F2F2F2")]),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#CCCCCC")),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
    ]))
    elements.append(t)
    elements.append(Spacer(1, 14))

    top_factors = result.get("top_factors", [])
    if top_factors:
        elements.append(Paragraph("Key Contributing Factors", section_style))
        factor_lines = [f"• {f['feature']}: {f['value']}" for f in top_factors]
        for line in factor_lines:
            elements.append(Paragraph(line, styles["Normal"]))
        elements.append(Spacer(1, 10))

    if notes:
        elements.append(Paragraph("Clinician Notes", section_style))
        elements.append(Paragraph(notes, styles["Normal"]))
        elements.append(Spacer(1, 10))

    elements.append(Spacer(1, 20))
    disclaimer = (
        "Disclaimer: This report is generated by a machine learning model trained on "
        "historical patient data and is intended for informational and educational "
        "purposes only. It is NOT a medical diagnosis and should not replace evaluation "
        "by a qualified healthcare professional. Always consult a physician for medical advice."
    )
    elements.append(Paragraph(disclaimer, ParagraphStyle(
        "Disclaimer", parent=styles["Normal"], fontSize=8, textColor=colors.grey
    )))

    doc.build(elements)

    # Track in CSV
    entry = pd.DataFrame([{
        "report_id": report_id,
        "timestamp": timestamp.strftime("%Y-%m-%d %H:%M:%S"),
        "patient_name": patient_name,
        "prediction": result.get("prediction"),
        "risk_percent": result.get("risk_percent"),
        "risk_level": result.get("risk_level"),
        "pdf_path": pdf_path,
    }])
    entry.to_csv(REPORTS_CSV, mode="a", header=False, index=False)

    return pdf_path


def load_report_index() -> pd.DataFrame:
    """Return the index of all generated reports."""
    _ensure_reports_file()
    df = pd.read_csv(REPORTS_CSV)
    if not df.empty:
        df["timestamp"] = pd.to_datetime(df["timestamp"])
    return df
